# Breast Cancer Progression Prediction using NHANES (1988–2018)

## Step 1: Dataset Exploration

The objective of this notebook is to determine whether the NHANES dataset contains sufficient information to build a Breast Cancer Progression Prediction model using Machine Learning Regression algorithms.

If the required progression variables are not available, an alternative dataset will be selected.

# Dataset Verification

Before developing the prediction model, the NHANES dataset was examined to verify whether it contains variables related to breast cancer.

The objective of this notebook is to identify breast cancer patients, validate the required variables, and ensure that the selected dataset is suitable for machine learning analysis.

In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
import os

path = r"C:\Users\nimis\OneDrive\Desktop\21743372"

os.chdir(path)

print(os.getcwd())

C:\Users\nimis\OneDrive\Desktop\21743372

In [3]:
questionnaire = pd.read_csv("questionnaire_clean.csv", low_memory=False)
response = pd.read_csv("response_clean.csv", low_memory=False)
mortality = pd.read_csv("mortality_clean.csv", low_memory=False)
demographics = pd.read_csv("demographics_clean.csv", low_memory=False)

In [4]:
import os

path = r"C:\Users\nimis\OneDrive\Desktop\21743372"

os.chdir(path)

print("Current Working Directory:")
print(os.getcwd())

Current Working Directory:
C:\Users\nimis\OneDrive\Desktop\21743372

In [5]:
print("Questionnaire:", questionnaire.shape)
print("Response:", response.shape)
print("Mortality:", mortality.shape)
print("Demographics:", demographics.shape)

Questionnaire: (134515, 1445)
Response: (131030, 1038)
Mortality: (135310, 16)
Demographics: (135310, 281)

In [6]:
print(questionnaire.columns.tolist())

['Unnamed: 0', 'SEQN', 'SEQN_new', 'SDDSRVYR', 'AGQ030', 'ALQ101', 'ALQ110', 'ALQ111', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'ALQ141Q', 'ALQ141U', 'ALQ151', 'ALQ155', 'ALQ160', 'ALQ170', 'ALQ270', 'ALQ280', 'ALQ290', 'BPD035', 'BPD058', 'BPD110A', 'BPD110B', 'BPD110C', 'BPD120', 'BPD130', 'BPD140', 'BPQ010', 'BPQ020', 'BPQ030', 'BPQ040A', 'BPQ040B', 'BPQ040C', 'BPQ040D', 'BPQ040E', 'BPQ040F', 'BPQ043A', 'BPQ043B', 'BPQ043C', 'BPQ043D', 'BPQ050A', 'BPQ050B', 'BPQ050C', 'BPQ050D', 'BPQ050E', 'BPQ052', 'BPQ056', 'BPQ057', 'BPQ059', 'BPQ060', 'BPQ070', 'BPQ080', 'BPQ090A', 'BPQ090B', 'BPQ090C', 'BPQ090D', 'BPQ100A', 'BPQ100B', 'BPQ100C', 'BPQ100D', 'DID040', 'DID040G', 'DID040Q', 'DID250', 'DID270', 'DID310D', 'DID310S', 'DID320', 'DID330', 'DID341', 'DID350', 'DIQ010', 'DIQ050', 'DIQ060', 'DIQ060G', 'DIQ060Q', 'DIQ060U', 'DIQ070', 'DIQ080', 'DIQ090', 'DIQ100', 'DIQ110', 'DIQ120', 'DIQ130', 'DIQ140', 'DIQ150', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ190A', 'DIQ190B', 'DIQ190C', 'DIQ200A', 'DIQ200B', 'DIQ200C', 'DIQ220', 'DIQ230', 'DIQ240', 'DIQ260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ290', 'DIQ300D', 'DIQ300S', 'DIQ350U', 'DIQ360', 'ECD010', 'ECD070A', 'ECD070B', 'ECQ020', 'ECQ030', 'ECQ040', 'ECQ060', 'ECQ080', 'ECQ090', 'ECQ100', 'ECQ110', 'ECQ130', 'ECQ140', 'ECQ150', 'FSQ121', 'HAB2', 'HAB3', 'HAB4', 'HAB5', 'HAB6S', 'HAB7', 'HAC1H', 'HAC1I', 'HAC1L', 'HAC1N', 'HAC2H', 'HAC3HR', 'HAC3IR', 'HAC3LR', 'HAC3NR', 'HAC3OR', 'HAC3OS', 'HAC5A1', 'HAC5A10', 'HAC5A11', 'HAC5A12', 'HAC5A2', 'HAC5A3', 'HAC5A4', 'HAC5A5', 'HAC5A6', 'HAC5A7', 'HAC5A8', 'HAC5A9', 'HAC5B1', 'HAC5B10', 'HAC5B11', 'HAC5B12', 'HAC5B2', 'HAC5B3', 'HAC5B4', 'HAC5B5', 'HAC5B6', 'HAC5B7', 'HAC5B8', 'HAC5B9', 'HAC7A', 'HAD11AS', 'HAD12S', 'HAD14', 'HAD3', 'HAD4', 'HAD7S', 'HAD8', 'HAE1', 'HAE10', 'HAE11A', 'HAE11B', 'HAE11C', 'HAE3', 'HAE4B', 'HAE4C', 'HAE4D', 'HAE4D1', 'HAE4D2', 'HAE4D3', 'HAE4D4', 'HAE4D5', 'HAE4D6', 'HAE5A', 'HAE5B', 'HAE5C', 'HAE5D1', 'HAE5D2', 'HAE5D3', 'HAE5D4', 'HAE5D5', 'HAE5D6', 'HAE6', 'HAE7', 'HAE8A', 'HAE8B', 'HAE8C', 'HAE8D', 'HAE9A', 'HAE9B', 'HAE9C', 'HAE9D', 'HAF1', 'HAF11', 'HAF13R', 'HAF14', 'HAF15', 'HAF16', 'HAF17', 'HAF18', 'HAF19', 'HAF2', 'HAF20', 'HAF21', 'HAF22', 'HAF23', 'HAF24', 'HAF25', 'HAF26', 'HAF27', 'HAF3', 'HAF4', 'HAF5', 'HAF6', 'HAF7A', 'HAF7B', 'HAF7C', 'HAF7D', 'HAF7E', 'HAF7F', 'HAF7G', 'HAF7H', 'HAF9', 'HAG1', 'HAG10A', 'HAG10B', 'HAG10C', 'HAG10D', 'HAG10E', 'HAG10F', 'HAG11', 'HAG12', 'HAG13', 'HAG14', 'HAG15', 'HAG16', 'HAG17A', 'HAG17AA', 'HAG17B', 'HAG17BB', 'HAG17C', 'HAG17CC', 'HAG17D', 'HAG17DD', 'HAG17E', 'HAG17EE', 'HAG17F', 'HAG17FF', 'HAG17G', 'HAG17H', 'HAG17I', 'HAG17J', 'HAG17K', 'HAG17L', 'HAG17M', 'HAG17N', 'HAG17O', 'HAG17P', 'HAG17Q', 'HAG17R', 'HAG17S', 'HAG17T', 'HAG17U', 'HAG17V', 'HAG17W', 'HAG17X', 'HAG17Y', 'HAG17Z', 'HAG18', 'HAG19A', 'HAG19AA', 'HAG19B', 'HAG19BB', 'HAG19C', 'HAG19CC', 'HAG19D', 'HAG19DD', 'HAG19E', 'HAG19EE', 'HAG19F', 'HAG19FF', 'HAG19G', 'HAG19H', 'HAG19I', 'HAG19J', 'HAG19K', 'HAG19L', 'HAG19M', 'HAG19N', 'HAG19O', 'HAG19P', 'HAG19Q', 'HAG19R', 'HAG19S', 'HAG19T', 'HAG19U', 'HAG19V', 'HAG19W', 'HAG19X', 'HAG19Y', 'HAG19Z', 'HAG2', 'HAG20', 'HAG21', 'HAG22', 'HAG23', 'HAG24', 'HAG25', 'HAG26', 'HAG27', 'HAG28', 'HAG29', 'HAG3', 'HAG30', 'HAG31', 'HAG32', 'HAG33', 'HAG34', 'HAG4A', 'HAG4B', 'HAG4C', 'HAG5A', 'HAG5B', 'HAG5C', 'HAG6A', 'HAG6B', 'HAG6C', 'HAG7', 'HAG8A', 'HAG8B', 'HAG8C', 'HAG8D', 'HAG8E', 'HAG8F', 'HAG9AR', 'HAG9BR', 'HAG9CR', 'HAG9DR', 'HAG9ER', 'HAG9FR', 'HAH1', 'HAH10', 'HAH11', 'HAH12', 'HAH13', 'HAH14', 'HAH15', 'HAH16', 'HAH17', 'HAH2', 'HAH3', 'HAH4', 'HAH5', 'HAH6', 'HAH7', 'HAH8', 'HAH9', 'HAJ0', 'HAJ10', 'HAJ11', 'HAJ14', 'HAJ15', 'HAJ2A', 'HAJ2B', 'HAJ2C', 'HAJ3S', 'HAJ4', 'HAJ5', 'HAJ6', 'HAJ8', 'HAK1', 'HAK10', 'HAK11', 'HAK12', 'HAK13', 'HAK14', 'HAK2', 'HAK3A', 'HAK3A1', 'HAK3B', 'HAK3B1R', 'HAK3C', 'HAK3C1R', 'HAK4', 'HAK5', 'HAK6', 'HAK7', 'HAK8', 'HAK9', 'HAL1', 'HAL10', 'HAL11A', 'HAL11B', 'HAL12', 'HAL13', 'HAL14A', 'HAL14B', 'HAL14C', 'HAL14D', 'HAL14E', 'HAL15A', 'HAL15B', 'HAL15C', 'HAL15D', 'HAL15E', 'HAL15F', 'HAL15G', 'HAL15H', 'HAL15I', 'HAL15J', 'HAL15K', 'HAL15L', 'HAL15M', 'HAL16A', 'HAL16B', 'HAL17', 'HAL18', 'HAL19A', 'HAL19B', 'HAL19C', 'HAL2', 'HAL20A', 'HAL20B', 'HAL20C', 'HAL3', 'HAL4', 'HAL5', 'HAL6', 'HAL7', 'HAL8', 'HAL9', 'HAM1', 'HAM10S', 'HAM11', 'HAM12', 'HAM13', 'HAM14', 'HAM15A', 'HAM15B', 'HAM15C', 'HAM15D', 'HAM15E', 'HAM15F', 'HAM15G', 'HAM15H', 'HAM15K', 'HAM15L', 'HAM15M', 'HAM15N', 'HAM15O', 'HAM15P', 'HAM15Q', 'HAM15R', 'HAM15S', 'HAM15T', 'HAM15U', 'HAM15V', 'HAM15W', 'HAM15X', 'HAM15Y', 'HAM15Z', 'HAM2', 'HAM3', 'HAM4', 'HAM5S', 'HAM6S', 'HAM7', 'HAM8S', 'HAM9S', 'HAN10A', 'HAN10B', 'HAN10C', 'HAN10D', 'HAN10E', 'HAN1AS', 'HAN1BS', 'HAN1C', 'HAN1D', 'HAN1ES', 'HAN1FS', 'HAN1GS', 'HAN1HS', 'HAN1IS', 'HAN2AS', 'HAN2BS', 'HAN2CS', 'HAN2DS', 'HAN2ES', 'HAN2FS', 'HAN2GS', 'HAN2HS', 'HAN2IS', 'HAN2JS', 'HAN3AS', 'HAN3BS', 'HAN3CS', 'HAN3DS', 'HAN3ES', 'HAN3FS', 'HAN4AS', 'HAN4BS', 'HAN4CS', 'HAN4DS', 'HAN4ES', 'HAN4FS', 'HAN4GS', 'HAN4HS', 'HAN4IS', 'HAN4JS', 'HAN4KS', 'HAN4LS', 'HAN5AS', 'HAN5BS', 'HAN5CS', 'HAN5DS', 'HAN5ES', 'HAN5FS', 'HAN5GS', 'HAN5HS', 'HAN5IS', 'HAN5JS', 'HAN5KS', 'HAN5LS', 'HAN6AS', 'HAN6BS', 'HAN6CS', 'HAN6DS', 'HAN6ES', 'HAN6FS', 'HAN6GS', 'HAN6HS', 'HAN6IS', 'HAN6JS', 'HAN7AS', 'HAN7BS', 'HAN7CS', 'HAN8', 'HAN8ACD', 'HAN8AS', 'HAN8BCD', 'HAN8BS', 'HAN8CCD', 'HAN8CS', 'HAN8DCD', 'HAN8DS', 'HAN8ECD', 'HAN8ES', 'HAN8FCD', 'HAN8FS', 'HAN9', 'HAP1', 'HAP10', 'HAP10A', 'HAP11', 'HAP12', 'HAP13', 'HAP14', 'HAP15', 'HAP16', 'HAP17A1', 'HAP17A2', 'HAP17A3', 'HAP17B', 'HAP18A', 'HAP18B', 'HAP18C', 'HAP18D', 'HAP18E', 'HAP19A', 'HAP19B', 'HAP19C', 'HAP1A', 'HAP2', 'HAP4', 'HAP5', 'HAP6', 'HAP7', 'HAP8', 'HAP9', 'HAQ1', 'HAQ2A', 'HAQ2B', 'HAQ2C', 'HAQ2D', 'HAQ2E', 'HAQ2F', 'HAQ2G', 'HAQ2I', 'HAQ2K', 'HAQ2L', 'HAQ3S', 'HAQ4', 'HAQ5', 'HAQ6', 'HAQ7', 'HAQ8', 'HAQ9', 'HAR1', 'HAR10', 'HAR11R', 'HAR12S', 'HAR13', 'HAR14', 'HAR15', 'HAR16', 'HAR17', 'HAR18AS', 'HAR18BS', 'HAR19A', 'HAR19B', 'HAR2', 'HAR20R', 'HAR21', 'HAR22', 'HAR23', 'HAR24', 'HAR25', 'HAR26', 'HAR27', 'HAR28', 'HAR3', 'HAR4S', 'HAR5', 'HAR6', 'HAR7S', 'HAR8', 'HAR9', 'HAT10', 'HAT10MET', 'HAT11S', 'HAT12', 'HAT12MET', 'HAT13S', 'HAT14', 'HAT14MET', 'HAT16MET', 'HAT18', 'HAT19CD', 'HAT19MET', 'HAT1MET', 'HAT1S', 'HAT2', 'HAT20S', 'HAT21CD', 'HAT21MET', 'HAT22S', 'HAT23CD', 'HAT23MET', 'HAT24S', 'HAT25CD', 'HAT25MET', 'HAT26S', 'HAT29', 'HAT2MET', 'HAT3S', 'HAT4MET', 'HAT6', 'HAT6MET', 'HAT7S', 'HAT8', 'HAT8MET', 'HAT9S', 'HAX11AG', 'HAX11AH', 'HAX11AI', 'HAX11AJ', 'HAX11AK', 'HAX11AL', 'HAX11AM', 'HAX11AN', 'HAX11AO', 'HAX11AP', 'HAX11AQ', 'HAX11AR', 'HAX11AS', 'HAX11AT', 'HAX11AU', 'HAX11AV', 'HAX12SG', 'HAX12SH', 'HAX12SI', 'HAX12SJ', 'HAX12SK', 'HAX12SL', 'HAX12SM', 'HAX12SN', 'HAX12SO', 'HAX12SP', 'HAX12SQ', 'HAX12SR', 'HAX12SS', 'HAX12ST', 'HAX12SU', 'HAX12SV', 'HAX13AG', 'HAX13AH', 'HAX13AI', 'HAX13AJ', 'HAX15SG', 'HAX15SH', 'HAX15SI', 'HAX15SJ', 'HAX16A1G', 'HAX16A1H', 'HAX16A1I', 'HAX16A1J', 'HAX16AG', 'HAX16AH', 'HAX16AI', 'HAX16AJ', 'HAX17SG', 'HAX17SH', 'HAX17SI', 'HAX17SJ', 'HAX18A', 'HAX18B', 'HAX18C', 'HAX18D', 'HAX18DB', 'HAX18E', 'HAX18EB', 'HAX18F', 'HAX18FB', 'HAX18G', 'HAX18GB', 'HAX19AS', 'HAX19BS', 'HAX19CS', 'HAX19DS', 'HAX19ES', 'HAX19FS', 'HAX19GS', 'HAX1A', 'HAX1B', 'HAX1C', 'HAX2A', 'HAX2B', 'HAX2C', 'HAX3CG', 'HAX3CH', 'HAX3CI', 'HAX3CJ', 'HAX3CK', 'HAX3CL', 'HAX3CM', 'HAX3CN', 'HAX3CO', 'HAX3CP', 'HAX3CQ', 'HAX3CR', 'HAX3CS', 'HAX3CT', 'HAX3CU', 'HAX3CV', 'HAX3CW', 'HAX3DG', 'HAX3DH', 'HAX3DI', 'HAX3DJ', 'HAX3DK', 'HAX3DL', 'HAX3DM', 'HAX3DN', 'HAX3DO', 'HAX3DP', 'HAX3DQ', 'HAX3DR', 'HAX3DS', 'HAX3DT', 'HAX3DU', 'HAX3DV', 'HAX3DW', 'HAX6SG', 'HAX6SH', 'HAX6SI', 'HAX6SJ', 'HAX6SK', 'HAX6SL', 'HAX6SM', 'HAX6SN', 'HAX6SO', 'HAX6SP', 'HAX6SQ', 'HAX6SR', 'HAX6SS', 'HAX6ST', 'HAX6SU', 'HAX6SV', 'HAX6SW', 'HAX8SG', 'HAX8SH', 'HAX8SI', 'HAX8SJ', 'HAX8SK', 'HAX8SL', 'HAX8SM', 'HAX8SN', 'HAX8SO', 'HAX8SP', 'HAX8SQ', 'HAX8SR', 'HAX8SS', 'HAX8ST', 'HAX8SU', 'HAX8SV', 'HAX8SW', 'HAX9DG', 'HAX9DH', 'HAX9DI', 'HAX9DJ', 'HAX9DK', 'HAX9DL', 'HAX9DM', 'HAX9DN', 'HAX9DO', 'HAX9DP', 'HAX9DQ', 'HAX9DR', 'HAX9DS', 'HAX9DT', 'HAX9DU', 'HAX9DV', 'HAX9EG', 'HAX9EH', 'HAX9EI', 'HAX9EJ', 'HAX9EK', 'HAX9EL', 'HAX9EM', 'HAX9EN', 'HAX9EO', 'HAX9EP', 'HAX9EQ', 'HAX9ER', 'HAX9ES', 'HAX9ET', 'HAX9EU', 'HAX9EV', 'HAX9FG', 'HAX9FH', 'HAX9FI', 'HAX9FJ', 'HAX9FK', 'HAX9FL', 'HAX9FM', 'HAX9FN', 'HAX9FO', 'HAX9FP', 'HAX9FQ', 'HAX9FR', 'HAX9FS', 'HAX9FT', 'HAX9FU', 'HAX9FV', 'HFB1', 'HFB10', 'HFB11', 'HFB11A', 'HFB11B', 'HFB11C', 'HFB11D', 'HFB11E', 'HFB12', 'HFB13', 'HFB14AB', 'HFB14AC', 'HFB14AD', 'HFB14AE', 'HFB14AF', 'HFB14AG', 'HFB14AI', 'HFB14BA', 'HFB14BB', 'HFB14BC', 'HFB14BD', 'HFB14BE', 'HFB14BF', 'HFB14BG', 'HFB14BH', 'HFB16A', 'HFB16B', 'HFB17', 'HFB2', 'HFB3', 'HFB4', 'HFB5', 'HFB6', 'HFB7', 'HFB8', 'HFB9', 'HFC6A1', 'HFC6B', 'HFC6B1', 'HFC6C', 'HFC6C1', 'HFC6D', 'HFC6D1', 'HFC6E', 'HFC6E1', 'HFF1', 'HFF2R', 'HFF3A', 'HFF3B', 'HFF3C', 'HFF3D', 'HFF3E', 'HFF3F', 'HSAQUEX', 'HSD010', 'HSQ470', 'HSQ480', 'HSQ490', 'HSQ493', 'HSQ496', 'HSQ500', 'HSQ510', 'HSQ520', 'HSQ571', 'HSQ580', 'HSQ590', 'MAPF12R', 'MAPF14', 'MAPF15', 'MAPF16', 'MAPF17', 'MAPF18S', 'MAPF22', 'MAPF32S', 'MAPF34A', 'MAPF34B', 'MAPF34CS', 'MAPF36', 'MAPF37', 'MAPF39S', 'MAPF42', 'MAPF43S', 'MAPF44', 'MAPF46', 'MAPF47S', 'MAPF48', 'MAPF50', 'MAPF51', 'MAPF53', 'MAPF54R', 'MAPF55', 'MAPF56', 'MAPF57', 'MCD093', 'MCD160M', 'MCD170M', 'MCD180A', 'MCD180B', 'MCD180C', 'MCD180D', 'MCD180E', 'MCD180F', 'MCD180G', 'MCD180K', 'MCD180L', 'MCD180M', 'MCD180N', 'MCD240A', 'MCD240B', 'MCD240C', 'MCD330', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'MCQ051', 'MCQ053', 'MCQ060', 'MCQ070', 'MCQ075', 'MCQ080', 'MCQ080E', 'MCQ082', 'MCQ083', 'MCQ084', 'MCQ086', 'MCQ090', 'MCQ092', 'MCQ100', 'MCQ110', 'MCQ114', 'MCQ117Q', 'MCQ117U', 'MCQ120B', 'MCQ120C', 'MCQ120D', 'MCQ140', 'MCQ149', 'MCQ150G', 'MCQ150Q', 'MCQ151', 'MCQ160A', 'MCQ160B', 'MCQ160C', 'MCQ160D', 'MCQ160E', 'MCQ160F', 'MCQ160G', 'MCQ160H', 'MCQ160J', 'MCQ160K', 'MCQ160L', 'MCQ160M', 'MCQ160N', 'MCQ160O', 'MCQ170H', 'MCQ170K', 'MCQ170L', 'MCQ170M', 'MCQ180H', 'MCQ195', 'MCQ200', 'MCQ203', 'MCQ206', 'MCQ210', 'MCQ220', 'MCQ230A', 'MCQ230B', 'MCQ230C', 'MCQ230D', 'MCQ240A', 'MCQ240AA', 'MCQ240B', 'MCQ240BB', 'MCQ240C', 'MCQ240CC', 'MCQ240D', 'MCQ240DD', 'MCQ240DK', 'MCQ240E', 'MCQ240F', 'MCQ240G', 'MCQ240H', 'MCQ240I', 'MCQ240J', 'MCQ240K', 'MCQ240L', 'MCQ240M', 'MCQ240N', 'MCQ240O', 'MCQ240P', 'MCQ240Q', 'MCQ240R', 'MCQ240S', 'MCQ240T', 'MCQ240U', 'MCQ240V', 'MCQ240W', 'MCQ240X', 'MCQ240Y', 'MCQ240Z', 'MCQ245A', 'MCQ245B', 'MCQ250B', 'MCQ250D', 'MCQ250E', 'MCQ250F', 'MCQ260AA', 'MCQ260AB', 'MCQ260AC', 'MCQ260AD', 'MCQ260AE', 'MCQ260AF', 'MCQ260AG', 'MCQ260AH', 'MCQ260AI', 'MCQ260BA', 'MCQ260BB', 'MCQ260BC', 'MCQ260BD', 'MCQ260BE', 'MCQ260BF', 'MCQ260BG', 'MCQ260BH', 'MCQ260BI', 'MCQ260CA', 'MCQ260CB', 'MCQ260CC', 'MCQ260CD', 'MCQ260CE', 'MCQ260CF', 'MCQ260CG', 'MCQ260CH', 'MCQ260CI', 'MCQ260DA', 'MCQ260DB', 'MCQ260DC', 'MCQ260DD', 'MCQ260DE', 'MCQ260DF', 'MCQ260DG', 'MCQ260DH', 'MCQ260DI', 'MCQ260EA', 'MCQ260EB', 'MCQ260EC', 'MCQ260ED', 'MCQ260EE', 'MCQ260EF', 'MCQ260EG', 'MCQ260EH', 'MCQ260EI', 'MCQ260FA', 'MCQ260FB', 'MCQ260FC', 'MCQ260FD', 'MCQ260FE', 'MCQ260FF', 'MCQ260FG', 'MCQ260FH', 'MCQ260FI', 'MCQ260GA', 'MCQ260GB', 'MCQ260GC', 'MCQ260GD', 'MCQ260GE', 'MCQ260GF', 'MCQ260GG', 'MCQ260GH', 'MCQ260GI', 'MCQ265', 'MCQ267E', 'MCQ268A', 'MCQ268B', 'MCQ268C', 'MCQ268D', 'MCQ270', 'MCQ280', 'MCQ290', 'MCQ300A', 'MCQ300B', 'MCQ300C', 'MCQ310', 'MCQ320', 'MCQ340', 'MCQ350', 'MCQ366A', 'MCQ366B', 'MCQ366C', 'MCQ366D', 'MCQ371A', 'MCQ371B', 'MCQ371C', 'MCQ371D', 'MCQ380', 'MCQ510A', 'MCQ510B', 'MCQ510C', 'MCQ510D', 'MCQ510E', 'MCQ510F', 'MCQ520', 'MCQ530', 'MCQ540', 'MCQ550', 'MCQ560', 'MCQ570', 'MYPC19', 'MYPC20', 'MYPC21', 'MYPC22', 'MYPC23S', 'MYPC27R', 'MYPC28', 'MYPC7S', 'OSQ230', 'PAAQUEX', 'PAD020', 'PAD120', 'PAD160', 'PAD200', 'PAD320', 'PAD440', 'PAD460', 'PAD480', 'PAD570', 'PAD615', 'PAD630', 'PAD645', 'PAD660', 'PAD675', 'PAD680', 'PAD733', 'PAQ050Q', 'PAQ050U', 'PAQ100', 'PAQ180', 'PAQ500', 'PAQ520', 'PAQ540', 'PAQ560', 'PAQ580', 'PAQ605', 'PAQ610', 'PAQ620', 'PAQ625', 'PAQ635', 'PAQ640', 'PAQ650', 'PAQ655', 'PAQ665', 'PAQ670', 'PAQ677', 'PAQ678', 'PAQ679', 'PAQ706', 'PAQ710', 'PAQ715', 'PAQ722', 'PAQ724A', 'PAQ724AA', 'PAQ724AB', 'PAQ724AC', 'PAQ724AD', 'PAQ724AE', 'PAQ724AF', 'PAQ724B', 'PAQ724C', 'PAQ724CM', 'PAQ724D', 'PAQ724E', 'PAQ724F', 'PAQ724G', 'PAQ724H', 'PAQ724I', 'PAQ724J', 'PAQ724K', 'PAQ724L', 'PAQ724M', 'PAQ724N', 'PAQ724O', 'PAQ724P', 'PAQ724Q', 'PAQ724R', 'PAQ724S', 'PAQ724T', 'PAQ724U', 'PAQ724V', 'PAQ724W', 'PAQ724X', 'PAQ724Y', 'PAQ724Z', 'PAQ731', 'PAQ740', 'PAQ742', 'PAQ744', 'PAQ746', 'PAQ748', 'PAQ750', 'PAQ755', 'PAQ759A', 'PAQ759B', 'PAQ759C', 'PAQ759D', 'PAQ759E', 'PAQ759F', 'PAQ759G', 'PAQ759H', 'PAQ759I', 'PAQ759J', 'PAQ759K', 'PAQ759L', 'PAQ759M', 'PAQ759N', 'PAQ759O', 'PAQ759P', 'PAQ759Q', 'PAQ759R', 'PAQ759S', 'PAQ759T', 'PAQ759U', 'PAQ759V', 'PAQ762', 'PAQ764', 'PAQ766', 'PAQ770', 'PAQ772A', 'PAQ772B', 'PAQ772C', 'RHD018', 'RHD043', 'RHD080', 'RHD120', 'RHD143', 'RHD152', 'RHD173', 'RHD180', 'RHD190', 'RHD230', 'RHD270', 'RHD280', 'RHD350', 'RHD442', 'RHD451', 'RHD470', 'RHQ010', 'RHQ020', 'RHQ030', 'RHQ031', 'RHQ051', 'RHQ060', 'RHQ070', 'RHQ074', 'RHQ076', 'RHQ078', 'RHQ090', 'RHQ100', 'RHQ110', 'RHQ131', 'RHQ160', 'RHQ162', 'RHQ163', 'RHQ166', 'RHQ169', 'RHQ171', 'RHQ172', 'RHQ197', 'RHQ200', 'RHQ205', 'RHQ210', 'RHQ240A', 'RHQ240B', 'RHQ240C', 'RHQ240D', 'RHQ240E', 'RHQ240F', 'RHQ250', 'RHQ260', 'RHQ291', 'RHQ300', 'RHQ305', 'RHQ310', 'RHQ320', 'RHQ330', 'RHQ332', 'RHQ340', 'RHQ360', 'RHQ370', 'RHQ380', 'RHQ390', 'RHQ395', 'RHQ420', 'RHQ430', 'RHQ460Q', 'RHQ460U', 'RHQ510', 'RHQ520', 'RHQ540', 'RHQ542A', 'RHQ542B', 'RHQ542C', 'RHQ542D', 'RHQ550', 'RHQ551A', 'RHQ551B', 'RHQ551C', 'RHQ551D', 'RHQ551E', 'RHQ551F', 'RHQ551G', 'RHQ554', 'RHQ556', 'RHQ558', 'RHQ560Q', 'RHQ560U', 'RHQ562', 'RHQ564', 'RHQ566', 'RHQ568Q', 'RHQ568U', 'RHQ570', 'RHQ572', 'RHQ574', 'RHQ576Q', 'RHQ576U', 'RHQ580', 'RHQ582', 'RHQ584', 'RHQ586Q', 'RHQ586U', 'RHQ596', 'RHQ598', 'RHQ600', 'RHQ602Q', 'RHQ602U', 'RHQ700', 'RHQ710A', 'RHQ710B', 'RHQ710C', 'RHQ710D', 'RHQ710E', 'RHQ710F', 'RHQ710G', 'RHQ720', 'RHQ730', 'RHQ740', 'RHQ750A', 'RHQ750B', 'RHQ750C', 'VNRHQ51', 'WHQ030E']

In [7]:
print(response.columns.tolist())

['SEQN', 'SEQN_new', 'SDDSRVYR', 'LBXSATSI2', 'LBXSATSI', 'LBXSATSI1', 'LBDSATLC', 'LBDSALSI2', 'LBXSAL2', 'URXUMA2', 'LBDSALSI', 'LBDSALSI1', 'LBXSAL', 'LBXSAL1', 'URXUMA', 'URXUMA1', 'URXUMS', 'LBXSAPSI2', 'LBXSAPSI', 'LBXSAPSI1', 'RFP2', 'TEP2', 'SSTOXG2', 'L1P', 'RFP', 'RFP1', 'HPP', 'TEP', 'TEP1', 'SSTOXG', 'SSTOXG1', 'TMP2', 'TMP', 'TMP1', 'HPPCAG', 'SSTOXAV', 'SSTOXM', 'AAP2', 'AAPSI2', 'LBDAPBSI2', 'LBXAPB2', 'AAP', 'AAP1', 'AAPSI', 'AAPSI1', 'LBDAPBSI', 'LBDAPBSI1', 'LBXAPB', 'LBXAPB1', 'LBXSASSI2', 'LBXSASSI', 'LBXSASSI1', 'LBXSC3SI2', 'LBXSC3SI', 'LBXSC3SI1', 'LBDSTBSI2', 'LBXSTB2', 'LBDSTBSI', 'LBDSTBSI1', 'LBXSTB', 'LBXSTB1', 'LBDSTBLC', 'BIAEXSTS', 'BIAREACT', 'BIAREACT1', 'BIAREACT2', 'BIARESIST', 'BIARESIST1', 'BIARESIST2', 'BIDALPHA', 'BIDCM', 'BIDECF', 'BIDFAT', 'BIDFC', 'BIDFFM', 'BIDFIT', 'BIDICF', 'BIDPFAT', 'BIDRECF', 'BIDRICF', 'BIDTBW', 'BIDTD', 'BIXC005K', 'BIXC006K', 'BIXC007K', 'BIXC008K', 'BIXC009K', 'BIXC010K', 'BIXC011K', 'BIXC012K', 'BIXC013K', 'BIXC014K', 'BIXC015K', 'BIXC016K', 'BIXC018K', 'BIXC020K', 'BIXC023K', 'BIXC025K', 'BIXC028K', 'BIXC031K', 'BIXC035K', 'BIXC039K', 'BIXC043K', 'BIXC050K', 'BIXC054K', 'BIXC060K', 'BIXC067K', 'BIXC075K', 'BIXC083K', 'BIXC093K', 'BIXC100K', 'BIXC115K', 'BIXC128K', 'BIXC143K', 'BIXC159K', 'BIXC177K', 'BIXC1M', 'BIXC200K', 'BIXC220K', 'BIXC245K', 'BIXC273K', 'BIXC304K', 'BIXC339K', 'BIXC378K', 'BIXC421K', 'BIXC469K', 'BIXC500K', 'BIXC582K', 'BIXC649K', 'BIXC723K', 'BIXC806K', 'BIXC898K', 'BIXS005K', 'BIXS006K', 'BIXS007K', 'BIXS008K', 'BIXS009K', 'BIXS010K', 'BIXS011K', 'BIXS012K', 'BIXS013K', 'BIXS014K', 'BIXS015K', 'BIXS016K', 'BIXS018K', 'BIXS020K', 'BIXS023K', 'BIXS025K', 'BIXS028K', 'BIXS031K', 'BIXS035K', 'BIXS039K', 'BIXS043K', 'BIXS050K', 'BIXS054K', 'BIXS060K', 'BIXS067K', 'BIXS075K', 'BIXS083K', 'BIXS093K', 'BIXS100K', 'BIXS115K', 'BIXS128K', 'BIXS143K', 'BIXS159K', 'BIXS177K', 'BIXS1M', 'BIXS200K', 'BIXS220K', 'BIXS245K', 'BIXS273K', 'BIXS304K', 'BIXS339K', 'BIXS378K', 'BIXS421K', 'BIXS469K', 'BIXS500K', 'BIXS582K', 'BIXS649K', 'BIXS723K', 'BIXS806K', 'BIXS898K', 'PEPPACE1', 'PEPPACE2', 'PERPACE', 'PERPREG', 'BPAARM', 'BPAARM1', 'BPAARM2', 'BPACSZ', 'BPACSZ1', 'BPACSZ2', 'BPAEN1', 'BPAEN2', 'BPAEN3', 'BPAEN4', 'BPQ150A', 'BPQ150B', 'BPQ150B1', 'BPQ150B2', 'BPQ150C', 'BPQ150D', 'BPXCHR', 'BPXDAR', 'BPXDB', 'BPXDI1', 'BPXDI11', 'BPXDI12', 'BPXDI1519', 'BPXDI15191', 'BPXDI15192', 'BPXDI2', 'BPXDI21', 'BPXDI22', 'BPXDI2519', 'BPXDI25191', 'BPXDI25192', 'BPXDI3', 'BPXDI31', 'BPXDI32', 'BPXDI3519', 'BPXDI35191', 'BPXDI35192', 'BPXDI4', 'BPXML1', 'BPXML11', 'BPXML12', 'BPXPLS', 'BPXPLS1', 'BPXPLS2', 'BPXPTY', 'BPXPULS', 'BPXPULS1', 'BPXPULS2', 'BPXSAR', 'BPXSY1', 'BPXSY11', 'BPXSY12', 'BPXSY2', 'BPXSY21', 'BPXSY22', 'BPXSY3', 'BPXSY31', 'BPXSY32', 'BPXSY4', 'PEASCCT1', 'PEASCST1', 'PEASCTM1', 'PEP6G41', 'PEP6G42', 'PEP6H411', 'PEP6H412', 'PEP6I41', 'PEP6I42', 'PEPNOK1R11', 'PEPNOK1R12', 'PERNOK5R', 'VNAVEBPXSY', 'VNAVEBPXSY1', 'VNAVEBPXSY2', 'VNLBAVEBPXDI', 'LBDSBUSI', 'LBDSBUSI2', 'LBXSBU2', 'LBDSBUSI1', 'LBXSBU', 'LBXSBU1', 'BMAAMP', 'BMAEXCMT', 'BMAEXLEN', 'BMAEXSTS', 'BMALLEXT', 'BMALLKNE', 'BMALOREX', 'BMALORKN', 'BMAULEXT', 'BMAUPLEL', 'BMAUPREL', 'BMAUREXT', 'BMDARMLF', 'BMDAVSAD', 'BMDBMIC', 'BMDCALFF', 'BMDLEGF', 'BMDRECUF', 'BMDSADCM', 'BMDSTATS', 'BMDSUBF', 'BMDTHICF', 'BMIARMC', 'BMIARML', 'BMICALF', 'BMIHEAD', 'BMIHIP', 'BMIHT', 'BMILEG', 'BMIRECUM', 'BMISUB', 'BMITHICR', 'BMITRI', 'BMIWAIST', 'BMIWT', 'BMPBIAC', 'BMPBIAC1', 'BMPBIAC2', 'BMPBIIL', 'BMPBIIL1', 'BMPBIIL2', 'BMPBUTTO', 'BMPBUTTO1', 'BMPBUTTO2', 'BMPELB', 'BMPELB1', 'BMPELB2', 'BMPHTFLG1', 'BMPHTFLG2', 'BMPHTIN', 'BMPHTIN1', 'BMPHTIN2', 'BMPKNEE', 'BMPKNEE1', 'BMPKNEE2', 'BMPRECFL1', 'BMPRECFL2', 'BMPSITHT', 'BMPSITHT1', 'BMPSITHT2', 'BMPSRWL', 'BMPSRWL1', 'BMPSRWL2', 'BMPSUP', 'BMPSUP1', 'BMPSUP2', 'BMPTECH11', 'BMPTECH12', 'BMPTHI', 'BMPTHI1', 'BMPTHI2', 'BMPWHR', 'BMPWHR1', 'BMPWHR2', 'BMPWRIST', 'BMPWRIST1', 'BMPWRIST2', 'BMPWTFLG1', 'BMPWTFLG2', 'BMPWTLBS', 'BMPWTLBS1', 'BMPWTLBS2', 'BMXARMC', 'BMXARMC1', 'BMXARMC2', 'BMXARML', 'BMXARML1', 'BMXARML2', 'BMXBMI', 'BMXBMI1', 'BMXBMI2', 'BMXCALF', 'BMXHEAD', 'BMXHEAD1', 'BMXHEAD2', 'BMXHIP', 'BMXHT', 'BMXHT1', 'BMXHT2', 'BMXLEG', 'BMXLEG1', 'BMXLEG2', 'BMXRECUM', 'BMXRECUM1', 'BMXRECUM2', 'BMXSAD1', 'BMXSAD2', 'BMXSAD3', 'BMXSAD4', 'BMXSUB', 'BMXSUB1', 'BMXSUB2', 'BMXTHICR', 'BMXTHICR1', 'BMXTHICR2', 'BMXTRI', 'BMXTRI1', 'BMXTRI2', 'BMXWAIST', 'BMXWAIST1', 'BMXWAIST2', 'BMXWT', 'BMXWT1', 'BMXWT2', 'WHD130', 'WHD1301', 'WHD1302', 'LBXBAP', 'LBXBAP1', 'LBXBAP2', 'LBXCRP2', 'LBXCRP', 'LBXCRP1', 'CVAARM', 'CVACUFF', 'CVAPROT', 'CVATEMP', 'CVAVEST', 'CVAWG1', 'CVAWS1', 'CVDESVO2', 'CVDEXCL1', 'CVDEXCL2', 'CVDEXCL3', 'CVDEXCL4', 'CVDEXCL5', 'CVDEXCL6', 'CVDEXCMT', 'CVDEXLEN', 'CVDEXMER', 'CVDEXSTS', 'CVDFITLV', 'CVDPMHR', 'CVDPROT', 'CVDR1DI', 'CVDR1HR', 'CVDR1SY', 'CVDR1TIM', 'CVDR2DI', 'CVDR2HR', 'CVDR2SY', 'CVDR2TIM', 'CVDR3DI', 'CVDR3HR', 'CVDR3SY', 'CVDR3TIM', 'CVDS1DI', 'CVDS1G', 'CVDS1HR', 'CVDS1S', 'CVDS1SY', 'CVDS1TIM', 'CVDS2DI', 'CVDS2G', 'CVDS2HR', 'CVDS2S', 'CVDS2SY', 'CVDS2TIM', 'CVDVOMAX', 'CVDWDI', 'CVDWHR', 'CVDWSY', 'CVDWTIM', 'CVQ220A', 'CVQ220B', 'CVQ220C', 'CVQ220E', 'CVQ220G', 'CVQ220H', 'CVQ220I', 'CVQ220J', 'CVQ220K', 'CVQ220L', 'CVQ220M', 'CVXPARC', 'CVXS1RPE', 'CVXS2RPE', 'CVXWRPE', 'LBXCD4', 'LBXCD8', 'LBDTCSI', 'LBDSTRSI', 'LBDTRSI', 'LBDHDD2', 'LBDHDDSI2', 'LBDLDL2', 'LBDLDLSI2', 'LBDSCHSI2', 'LBDSTRSI2', 'LBDTCSI2', 'LBDTRSI2', 'LBXSCH2', 'LBXSTR2', 'LBXTC2', 'LBXTR2', 'LBDHDD', 'LBDHDD1', 'LBDHDDSI', 'LBDHDDSI1', 'LBDLDL', 'LBDLDL1', 'LBDLDLSI', 'LBDLDLSI1', 'LBDSCHSI', 'LBDSCHSI1', 'LBDSTRSI1', 'LBDTCSI1', 'LBDTRSI1', 'LBXSCH', 'LBXSCH1', 'LBXSTR', 'LBXSTR1', 'LBXTC', 'LBXTC1', 'LBXTR', 'LBXTR1', 'VNLDHDLRATIO', 'VNTOTHDRATIO', 'WTSAF2YR', 'WTSAF4YR', 'ANP2', 'BAP2', 'BLP2', 'BSP2', 'GRP2', 'GRPPCNT2', 'HGPSI2', 'HTPSI2', 'HZP2', 'LAP2', 'LBDLYMNO2', 'LBXBAPCT2', 'LBXEOPCT2', 'LBXHGB2', 'LBXLYPCT2', 'LBXMC2', 'LBXMCHSI2', 'LBXMCVSI2', 'LBXMOPCT2', 'LBXMPSI2', 'LBXNEPCT2', 'LBXPLTSI2', 'LBXRBCSI2', 'LBXRDW2', 'LBXWBCSI2', 'LMPDIF2', 'MEP2', 'MHPSI2', 'MIP2', 'MLP2', 'MOP2', 'MOPPCNT2', 'MRP2', 'PKP2', 'PLP2', 'POP2', 'PRP2', 'RCP2', 'RWPSI2', 'SHP2', 'SIP2', 'TTP2', 'TXP2', 'VNHEMACRIT2', 'VUP2', 'DWP2', 'ANP', 'ANP1', 'BAP', 'BAP1', 'BLP', 'BLP1', 'BSP1', 'GRP', 'GRP1', 'GRPPCNT', 'GRPPCNT1', 'HGPSI', 'HGPSI1', 'HTPSI1', 'HZP', 'HZP1', 'LAP', 'LAP1', 'LBDLYMNO', 'LBDLYMNO1', 'LBXBAPCT', 'LBXBAPCT1', 'LBXEOPCT', 'LBXEOPCT1', 'LBXHGB', 'LBXHGB1', 'LBXLYPCT', 'LBXLYPCT1', 'LBXMC', 'LBXMC1', 'LBXMCHSI', 'LBXMCHSI1', 'LBXMCVSI', 'LBXMCVSI1', 'LBXMOPCT', 'LBXMOPCT1', 'LBXMPSI', 'LBXMPSI1', 'LBXNEPCT', 'LBXNEPCT1', 'LBXPLTSI', 'LBXPLTSI1', 'LBXRBCSI', 'LBXRBCSI1', 'LBXRDW', 'LBXRDW1', 'LBXWBCSI', 'LBXWBCSI1', 'LMPDIF', 'LMPDIF1', 'MEP', 'MEP1', 'MHPSI', 'MHPSI1', 'MIP', 'MIP1', 'MLP', 'MLP1', 'MOP', 'MOP1', 'MOPPCNT', 'MOPPCNT1', 'MRP', 'MRP1', 'PKP', 'PKP1', 'PLP', 'PLP1', 'POP', 'POP1', 'PRP', 'PRP1', 'RCP', 'RCP1', 'RWPSI', 'RWPSI1', 'SHP', 'SHP1', 'SIP', 'SIP1', 'TTP', 'TTP1', 'TXP', 'TXP1', 'VNHEMACRIT', 'VNHEMACRIT1', 'VUP', 'VUP1', 'DWP', 'DWP1', 'LBDBANO', 'LBDEONO', 'LBDMONO', 'LBDNENO', 'LBDBANO1', 'LBDBANO2', 'LBDEONO1', 'LBDEONO2', 'LBDMONO1', 'LBDMONO2', 'LBDNENO1', 'LBDNENO2', 'LBXPT21', 'LBXNRBC', 'LBXSCK', 'URXUCR', 'LBXSCR2', 'URXUCR2', 'LBXSCR', 'LBXSCR1', 'URXUCR1', 'CMPODM', 'CMPRFPX', 'SSCMIGGA', 'SSCMIGM', 'SSCMV', 'SSCMVOD', 'SSCMVOD1', 'SSCMVOD2', 'G1PCODE2', 'GHPMETH2', 'I1P2PFLG2', 'G1PCODE1', 'GHPMETH1', 'I1P2PFLG1', 'SSEBV', 'SSEBVIND', 'LBDEPPSI', 'LBDEPPSI2', 'LBXEPP', 'LBXEPP2', 'LBDEPPSI1', 'LBXEPP1', 'LBXFER', 'LBDFERSI2', 'LBXFER2', 'LBDFERSI', 'LBDFERSI1', 'LBXFER1', 'LBDFBSI', 'LBDFBSI2', 'LBXFB2', 'LBDFBSI1', 'LBXFB', 'LBXFB1', 'LBDFOT2', 'LBDFOTSI2', 'LBDRFO2', 'LBDRFOSI2', 'LBDFOT', 'LBDFOT1', 'LBDFOTSI', 'LBDFOTSI1', 'LBDRFO', 'LBDRFO1', 'LBDRFOSI', 'LBDRFOSI1', 'LBDFSHSI2', 'LBDFSHSI1', 'VNAVEFHPSI', 'LBDFSHSI', 'LBXFSH', 'LBXFSH1', 'LBXFSH2', 'LBXSGTSI', 'LBXSGTSI2', 'LBXSGTSI1', 'LBDSGTLC', 'LBDSGBSI2', 'LBXSGB2', 'LBDSGBSI', 'LBDSGBSI1', 'LBXSGB', 'LBXSGB1', 'VNEGFR', 'VNEGFRADJ', 'LBXGH2', 'LBXGH', 'LBXGH1', 'LBDHBG2', 'LBDHCV2', 'LBDHD2', 'LBXHA2', 'LBXHBC2', 'LBXHBS2', 'LBDHBG', 'LBDHBG1', 'LBDHCV', 'LBDHCV1', 'LBDHD', 'LBDHD1', 'LBXHA', 'LBXHA1', 'LBXHBC', 'LBXHBC1', 'LBXHBS', 'LBXHBS1', 'LBXHE12', 'LBXHE22', 'LBXHE1', 'LBXHE11', 'LBXHE2', 'LBXHE21', 'LBXHP1', 'LBDHRPLC', 'LBXHSCRP', 'LBDHI', 'LBXHIV1', 'LBXHIV2', 'LBXHNAT', 'LBXHCY2', 'LBXHCY', 'LBXHCY1', 'LBDIRNSI', 'LBDPCT', 'LBDIRNSI2', 'LBDPCT2', 'LBDSIRSI2', 'LBDTIBSI2', 'LBXIRN2', 'LBXSIR2', 'LBXTIB2', 'LBDIRNSI1', 'LBDPCT1', 'LBDSIRSI', 'LBDSIRSI1', 'LBDTIBSI', 'LBDTIBSI1', 'LBXIRN', 'LBXIRN1', 'LBXSIR', 'LBXSIR1', 'LBXTIB', 'LBXTIB1', 'LBXSLDSI2', 'LBXSLDSI', 'LBXSLDSI1', 'LPP2', 'LPPSI2', 'LPP', 'LPP1', 'LPPSI', 'LPPSI1', 'LBDLHSI2', 'LBDLHSI', 'LBDLHSI1', 'LBXLH', 'LBXLH1', 'LBXLH2', 'LBDRUIU2', 'LBXRUB2', 'LBXVAR2', 'LBDRUIU', 'LBDRUIU1', 'LBXRUB', 'LBXRUB1', 'LBXVAR', 'LBXVAR1', 'LBXVAR3', 'VARICELL', 'VNAVEICPSI2', 'VNAVEICPSI', 'VNAVEICPSI1', 'LBXGLT', 'WTSOG2YR', 'GTDBL2MN', 'GTDCODE', 'GTDDR1MN', 'GTDDR2MN', 'GTDSCMMN', 'GTXDRANK', 'LBXSOSSI2', 'LBXSOSSI', 'LBXSOSSI1', 'PHPBEST2', 'PHPCHM22', 'PHPDRDA2', 'PHPDRIN2', 'PHPDRTI2', 'PHPHEMO2', 'PHPINSU2', 'PHPLANG2', 'PHPSNDA2', 'PHPSNTI2', 'PHPBEST1', 'PHPCHM21', 'PHPDRDA1', 'PHPDRIN1', 'PHPDRTI1', 'PHPHEMO1', 'PHPINSU1', 'PHPLANG1', 'PHPSNDA1', 'PHPSNTI1', 'DIQ050', 'LBDSPHSI', 'LBDSPHSI1', 'LBDSPHSI2', 'LBXSPH2', 'LBXSPH', 'LBXSPH1', 'LBDINSI', 'LBDINSI2', 'LBDINSI4', 'LBXGLU3', 'LBXGLU4', 'LBXGLUSI3', 'LBXGLUSI4', 'LBXIN2', 'LBXIN4', 'LBXSGL2', 'PHAFSTHR2', 'LBDINSI1', 'LBDINSI3', 'LBXGLU', 'LBXGLU1', 'LBXGLU2', 'LBXGLUSI', 'LBXGLUSI1', 'LBXGLUSI2', 'LBXIN', 'LBXIN1', 'LBXIN3', 'LBXSGL', 'LBXSGL1', 'PHAFSTHR', 'PHAFSTHR1', 'PHAFSTMN', 'PHAFSTMN1', 'PHAFSTMN2', 'LBDINLC', 'LBXCP3', 'LBXCP4', 'LBXCPSI2', 'LBXCPSI4', 'LBXCP', 'LBXCP1', 'LBXCP2', 'LBXCPSI', 'LBXCPSI1', 'LBXCPSI3', 'LBDESTLC', 'LBDSHGLC', 'LBDTSTLC', 'LBXEST', 'LBXSHBG', 'LBXTST', 'ENQ010', 'ENQ020', 'ENQ100', 'ENQ1001', 'ENQ1002', 'HXREJ6A2', 'SPDBACC', 'SPDBRONC', 'SPDNACC', 'SPPEXPIR', 'SPPEXPIR1', 'SPPEXPIR2', 'SPPFEF75', 'SPPFEF751', 'SPPFEF752', 'SPPFEV05', 'SPPFEV051', 'SPPFEV052', 'SPPFEV1', 'SPPFEV11', 'SPPFEV12', 'SPPFEV3', 'SPPFEV31', 'SPPFEV32', 'SPPFEV6', 'SPPFEV61', 'SPPFEV62', 'SPPFVC', 'SPPFVC1', 'SPPFVC2', 'SPPMMEF', 'SPPMMEF1', 'SPPMMEF2', 'SPPPEAK', 'SPPPEAK1', 'SPPPEAK2', 'SPPQ21', 'SPPQ22', 'SPPQ31', 'SPPQ32', 'SPPQ41', 'SPPQ42', 'SPPRELIA1', 'SPPRELIA2', 'SPPREPRO1', 'SPPREPRO2', 'SPPTECH11', 'SPPTECH22', 'SPPTEMP', 'SPPTEMP1', 'SPPTEMP2', 'SPPTIME1', 'SPPTIME2', 'SPPTRIAL1', 'SPPTRIAL2', 'SPPTYPE1', 'SPPTYPE2', 'SPQ010', 'SPQ020', 'SPQ030', 'SPQ040', 'SPQ050', 'SPQ0501', 'SPQ0502', 'SPQ060', 'SPQ070A', 'SPQ070B', 'SPQ070C', 'SPQ070D', 'SPQ070E', 'SPQ080', 'SPQ090', 'SPQ100', 'SPXBCMT', 'SPXBEV', 'SPXBF257', 'SPXBFET', 'SPXBFEV1', 'SPXBFEV3', 'SPXBFEV5', 'SPXBFEV6', 'SPXBFEV7', 'SPXBFVC', 'SPXBPEF', 'SPXBQEFF', 'SPXBQFV1', 'SPXBQFVC', 'SPXBSTAT', 'SPXNCMT', 'SPXNEV', 'SPXNF257', 'SPXNFET', 'SPXNFEV1', 'SPXNFEV3', 'SPXNFEV5', 'SPXNFEV6', 'SPXNFEV7', 'SPXNFVC', 'SPXNPEF', 'SPXNQEFF', 'SPXNQFV1', 'SPXNQFVC', 'SPXNSTAT', 'LBXT4F', 'LBDT4FSI', 'LBXT3F', 'LBXTGN', 'LBXATG', 'LBXATG1', 'LBXATG2', 'LBDTGNSI', 'LBXTPO', 'LBXTSH', 'LBXTSH1', 'LBXTSH2', 'LBDTSHSI', 'LBDTSHSI1', 'LBDTSHSI2', 'LBXTT4', 'LBDT4SI', 'LBXTT3', 'LBDTT3SI', 'LBDSTPSI2', 'LBXSTP2', 'LBDSTPSI', 'LBDSTPSI1', 'LBXSTP', 'LBXSTP1', 'LBXTFR', 'LBDSUASI2', 'LBXSUA2', 'LBDSUASI', 'LBDSUASI1', 'LBXSUA', 'LBXSUA1', 'URDNT', 'URDNT1', 'URDNT2']

In [8]:
print(mortality.columns.tolist())

['Unnamed: 0', 'SEQN', 'SEQN_new', 'ELIGSTAT', 'MORTSTAT', 'UCOD_LEADING', 'DIABETES', 'HYPERTEN', 'PERMTH_INT', 'PERMTH_EXM', 'SDDSRVYR', 'VNELIGSTAT', 'VNMORTSTAT', 'VNUCOD_LEADING', 'VNDIABETES', 'VNHYPERTEN']

In [9]:
print(demographics.columns.tolist())

['SEQN', 'SEQN_new', 'AIALANGA', 'DMAETHN', 'DMAETHNR', 'DMARACE', 'DMARACER', 'DMDBORN4', 'DMDCITZN', 'DMDEDUC', 'DMDEDUC2', 'DMDEDUC3', 'DMDFMSIZ', 'DMDHHSIZ', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRAGE', 'DMDHRBR4', 'DMDHREDU', 'DMDHRGND', 'DMDHRMAR', 'DMDHSEDU', 'DMDMARTL', 'DMDSCHOL', 'DMDYRSUS', 'DMPCNTYR', 'DMPCREGN', 'DMPFIPSR', 'DMPFSEQ', 'DMPMETRO', 'DMQADFC', 'DMQMILIZ', 'FIAINTRP', 'FIALANG', 'FIAPROXY', 'HAA1', 'HAA2', 'HAA2A', 'HAA3', 'HAA4', 'HAA5', 'HAA6A', 'HAA6B', 'HAA6C', 'HAA6D', 'HAD2', 'HAINTVR', 'HALANG', 'HAV10R', 'HAV11', 'HAV1S', 'HAV2S', 'HAV3S', 'HAV4S', 'HAV5', 'HAV6S', 'HAV7R', 'HAV8', 'HAV9', 'HAVERS', 'HAY10', 'HAY6', 'HAY7', 'HAY8', 'HAY9', 'HFA13', 'HFAGERR', 'HFC1', 'HFC10', 'HFC11', 'HFC7S', 'HFC8S', 'HFC9', 'HFE1', 'HFE10', 'HFE11', 'HFE12', 'HFE13', 'HFE14', 'HFE15', 'HFE16', 'HFE17', 'HFE18', 'HFE2', 'HFE3', 'HFE4', 'HFE5', 'HFE6', 'HFE7', 'HFE8A', 'HFE8B', 'HFE8C', 'HFE8D', 'HFE8E', 'HFE9', 'HFF10', 'HFF11', 'HFF12A', 'HFF12B', 'HFF13A', 'HFF13B', 'HFF13DA', 'HFF13DB', 'HFF13E', 'HFF14A', 'HFF14B', 'HFF14D', 'HFF15A', 'HFF15B', 'HFF16A', 'HFF16B', 'HFF16D', 'HFF16E', 'HFF17A', 'HFF17B', 'HFF18', 'HFF20R', 'HFF4', 'HFF5', 'HFF6A', 'HFF6B', 'HFF6C', 'HFF6D', 'HFF7', 'HFF8', 'HFF9', 'HFHEMPL', 'HFHMLSV', 'HFHSEQN', 'HFINTVR', 'HFRELR', 'HFVERS', 'HSAGEU', 'HSAITMOR', 'HSDOIMO', 'HXPSESSR', 'HXPTIDW', 'HXPTIMO', 'HYAITMO', 'INDFMIN2', 'INDFMPIR', 'INDHHIN2', 'MIAINTRP', 'MIALANG', 'MIAPROXY', 'MXPSESSR', 'MXPTIDW', 'MXPTIMO', 'RIAGENDR', 'RIDAGEMN', 'RIDAGEYR', 'RIDEXAGM', 'RIDEXAGY', 'RIDEXMON', 'RIDEXPRG', 'RIDPREG', 'RIDRETH1', 'RIDRETH2', 'RIDRETH3', 'RIDSTATR', 'SDDSRVYR', 'SDJ1REPN', 'SDMVPSU', 'SDMVSTRA', 'SDPPHASE', 'SDPPSU1', 'SDPPSU2', 'SDPSTRA1', 'SDPSTRA2', 'SIAINTRP', 'SIALANG', 'SIAPROXY', 'WTINT2YR', 'WTINT4YR', 'WTIREP01', 'WTIREP02', 'WTIREP03', 'WTIREP04', 'WTIREP05', 'WTIREP06', 'WTIREP07', 'WTIREP08', 'WTIREP09', 'WTIREP10', 'WTIREP11', 'WTIREP12', 'WTIREP13', 'WTIREP14', 'WTIREP15', 'WTIREP16', 'WTIREP17', 'WTIREP18', 'WTIREP19', 'WTIREP20', 'WTIREP21', 'WTIREP22', 'WTIREP23', 'WTIREP24', 'WTIREP25', 'WTIREP26', 'WTIREP27', 'WTIREP28', 'WTIREP29', 'WTIREP30', 'WTIREP31', 'WTIREP32', 'WTIREP33', 'WTIREP34', 'WTIREP35', 'WTIREP36', 'WTIREP37', 'WTIREP38', 'WTIREP39', 'WTIREP40', 'WTIREP41', 'WTIREP42', 'WTIREP43', 'WTIREP44', 'WTIREP45', 'WTIREP46', 'WTIREP47', 'WTIREP48', 'WTIREP49', 'WTIREP50', 'WTIREP51', 'WTIREP52', 'WTMEC2YR', 'WTMEC4YR', 'WTMREP01', 'WTMREP02', 'WTMREP03', 'WTMREP04', 'WTMREP05', 'WTMREP06', 'WTMREP07', 'WTMREP08', 'WTMREP09', 'WTMREP10', 'WTMREP11', 'WTMREP12', 'WTMREP13', 'WTMREP14', 'WTMREP15', 'WTMREP16', 'WTMREP17', 'WTMREP18', 'WTMREP19', 'WTMREP20', 'WTMREP21', 'WTMREP22', 'WTMREP23', 'WTMREP24', 'WTMREP25', 'WTMREP26', 'WTMREP27', 'WTMREP28', 'WTMREP29', 'WTMREP30', 'WTMREP31', 'WTMREP32', 'WTMREP33', 'WTMREP34', 'WTMREP35', 'WTMREP36', 'WTMREP37', 'WTMREP38', 'WTMREP39', 'WTMREP40', 'WTMREP41', 'WTMREP42', 'WTMREP43', 'WTMREP44', 'WTMREP45', 'WTMREP46', 'WTMREP47', 'WTMREP48', 'WTMREP49', 'WTMREP50', 'WTMREP51', 'WTMREP52']

In [10]:
keywords = [
    "breast",
    "cancer",
    "tumor",
    "malignant",
    "survival",
    "mort",
    "diagnosis",
    "stage",
    "metast",
    "oncology"
]

datasets = {
    "Questionnaire": questionnaire,
    "Response": response,
    "Mortality": mortality,
    "Demographics": demographics
}

for name, df in datasets.items():
    print(f"\n{name}")
    found = []

    for col in df.columns:
        for key in keywords:
            if key in col.lower():
                found.append(col)
                break

    if found:
        print(found)
    else:
        print("No matching columns found.")

Questionnaire
No matching columns found.

Response
No matching columns found.

Mortality
['MORTSTAT', 'VNMORTSTAT']

Demographics
No matching columns found.

In [11]:
# Search for variables beginning with common NHANES prefixes
prefixes = ["MCQ", "CNQ", "DIQ", "KIQ", "WHQ", "RHQ", "HUQ", "OCQ", "BPQ"]

for name, df in datasets.items():
    print(f"\n{name}")
    cols = [col for col in df.columns if any(col.startswith(p) for p in prefixes)]
    print(cols[:100])   # Show first 100 matching columns
    print(f"Total matching columns: {len(cols)}")

Questionnaire
['BPQ010', 'BPQ020', 'BPQ030', 'BPQ040A', 'BPQ040B', 'BPQ040C', 'BPQ040D', 'BPQ040E', 'BPQ040F', 'BPQ043A', 'BPQ043B', 'BPQ043C', 'BPQ043D', 'BPQ050A', 'BPQ050B', 'BPQ050C', 'BPQ050D', 'BPQ050E', 'BPQ052', 'BPQ056', 'BPQ057', 'BPQ059', 'BPQ060', 'BPQ070', 'BPQ080', 'BPQ090A', 'BPQ090B', 'BPQ090C', 'BPQ090D', 'BPQ100A', 'BPQ100B', 'BPQ100C', 'BPQ100D', 'DIQ010', 'DIQ050', 'DIQ060', 'DIQ060G', 'DIQ060Q', 'DIQ060U', 'DIQ070', 'DIQ080', 'DIQ090', 'DIQ100', 'DIQ110', 'DIQ120', 'DIQ130', 'DIQ140', 'DIQ150', 'DIQ160', 'DIQ170', 'DIQ172', 'DIQ175A', 'DIQ175B', 'DIQ175C', 'DIQ175D', 'DIQ175E', 'DIQ175F', 'DIQ175G', 'DIQ175H', 'DIQ175I', 'DIQ175J', 'DIQ175K', 'DIQ175L', 'DIQ175M', 'DIQ175N', 'DIQ175O', 'DIQ175P', 'DIQ175Q', 'DIQ175R', 'DIQ175S', 'DIQ175T', 'DIQ175U', 'DIQ175V', 'DIQ175W', 'DIQ175X', 'DIQ180', 'DIQ190A', 'DIQ190B', 'DIQ190C', 'DIQ200A', 'DIQ200B', 'DIQ200C', 'DIQ220', 'DIQ230', 'DIQ240', 'DIQ260', 'DIQ260U', 'DIQ275', 'DIQ280', 'DIQ290', 'DIQ300D', 'DIQ300S', 'DIQ350U', 'DIQ360', 'MCQ010', 'MCQ025', 'MCQ035', 'MCQ040', 'MCQ050', 'MCQ051']
Total matching columns: 396

Response
['BPQ150A', 'BPQ150B', 'BPQ150B1', 'BPQ150B2', 'BPQ150C', 'BPQ150D', 'DIQ050']
Total matching columns: 7

Mortality
[]
Total matching columns: 0

Demographics
[]
Total matching columns: 0

In [12]:
questionnaire.filter(regex='MCQ').head()

,MCQ010,MCQ025,MCQ035,MCQ040,MCQ050,MCQ051,MCQ053,MCQ060,MCQ070,MCQ075,MCQ080,MCQ080E,MCQ082,MCQ083,MCQ084,MCQ086,MCQ090,MCQ092,MCQ100,MCQ110,MCQ114,MCQ117Q,MCQ117U,MCQ120B,MCQ120C,MCQ120D,MCQ140,MCQ149,MCQ150G,MCQ150Q,MCQ151,MCQ160A,MCQ160B,MCQ160C,MCQ160D,MCQ160E,MCQ160F,MCQ160G,MCQ160H,MCQ160J,MCQ160K,MCQ160L,MCQ160M,MCQ160N,MCQ160O,MCQ170H,MCQ170K,MCQ170L,MCQ170M,MCQ180H,MCQ195,MCQ200,MCQ203,MCQ206,MCQ210,MCQ220,MCQ230A,MCQ230B,MCQ230C,MCQ230D,MCQ240A,MCQ240AA,MCQ240B,MCQ240BB,MCQ240C,MCQ240CC,MCQ240D,MCQ240DD,MCQ240DK,MCQ240E,MCQ240F,MCQ240G,MCQ240H,MCQ240I,MCQ240J,MCQ240K,MCQ240L,MCQ240M,MCQ240N,MCQ240O,MCQ240P,MCQ240Q,MCQ240R,MCQ240S,MCQ240T,MCQ240U,MCQ240V,MCQ240W,MCQ240X,MCQ240Y,MCQ240Z,MCQ245A,MCQ245B,MCQ250B,MCQ250D,MCQ250E,MCQ250F,MCQ260AA,MCQ260AB,MCQ260AC,MCQ260AD,MCQ260AE,MCQ260AF,MCQ260AG,MCQ260AH,MCQ260AI,MCQ260BA,MCQ260BB,MCQ260BC,MCQ260BD,MCQ260BE,MCQ260BF,MCQ260BG,MCQ260BH,MCQ260BI,MCQ260CA,MCQ260CB,MCQ260CC,MCQ260CD,MCQ260CE,MCQ260CF,MCQ260CG,MCQ260CH,MCQ260CI,MCQ260DA,MCQ260DB,MCQ260DC,MCQ260DD,MCQ260DE,MCQ260DF,MCQ260DG,MCQ260DH,MCQ260DI,MCQ260EA,MCQ260EB,MCQ260EC,MCQ260ED,MCQ260EE,MCQ260EF,MCQ260EG,MCQ260EH,MCQ260EI,MCQ260FA,MCQ260FB,MCQ260FC,MCQ260FD,MCQ260FE,MCQ260FF,MCQ260FG,MCQ260FH,MCQ260FI,MCQ260GA,MCQ260GB,MCQ260GC,MCQ260GD,MCQ260GE,MCQ260GF,MCQ260GG,MCQ260GH,MCQ260GI,MCQ265,MCQ267E,MCQ268A,MCQ268B,MCQ268C,MCQ268D,MCQ270,MCQ280,MCQ290,MCQ300A,MCQ300B,MCQ300C,MCQ310,MCQ320,MCQ340,MCQ350,MCQ366A,MCQ366B,MCQ366C,MCQ366D,MCQ371A,MCQ371B,MCQ371C,MCQ371D,MCQ380,MCQ510A,MCQ510B,MCQ510C,MCQ510D,MCQ510E,MCQ510F,MCQ520,MCQ530,MCQ540,MCQ550,MCQ560,MCQ570
0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN
1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,2.0,2.0,NaN
2,1.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN
3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN
4,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,78.0,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN

In [13]:
# Display the distribution of important MCQ variables
variables = [
    "MCQ220",
    "MCQ230A",
    "MCQ240A",
    "MCQ240B",
    "MCQ240C",
    "MCQ240D"
]

for var in variables:
    if var in questionnaire.columns:
        print(f"\n{'='*50}")
        print(f"Variable: {var}")
        print(questionnaire[var].value_counts(dropna=False))

==================================================
Variable: MCQ220
MCQ220
2.0    69121
NaN    59388
1.0     5946
9.0       59
7.0        1
Name: count, dtype: int64

==================================================
Variable: MCQ230A
MCQ230A
NaN     129351
14.0       794
30.0       786
32.0       752
33.0       391
16.0       347
15.0       327
25.0       291
39.0       222
38.0       209
23.0       133
10.0       121
28.0       114
24.0       108
37.0        96
19.0        93
21.0        51
35.0        42
99.0        37
12.0        31
26.0        30
36.0        30
17.0        28
20.0        25
22.0        24
31.0        22
13.0        21
34.0        12
29.0        12
11.0        11
18.0         2
9.0          1
27.0         1
Name: count, dtype: int64

==================================================
Variable: MCQ240A
MCQ240A
NaN     134400
80.0        20
70.0         7
65.0         5
72.0         5
76.0         4
60.0         4
68.0         4
16.0         4
63.0         4
55.0         4
78.0         4
85.0         3
66.0         3
73.0         3
79.0         3
59.0         3
75.0         3
50.0         3
38.0         2
56.0         2
57.0         2
54.0         2
36.0         2
53.0         2
69.0         2
58.0         2
52.0         2
46.0         1
71.0         1
64.0         1
43.0         1
49.0         1
48.0         1
62.0         1
67.0         1
34.0         1
83.0         1
77.0         1
Name: count, dtype: int64

==================================================
Variable: MCQ240B
MCQ240B
NaN        134501
16.0            2
63.0            2
57.0            1
66.0            1
62.0            1
60.0            1
40.0            1
58.0            1
46.0            1
70.0            1
99999.0         1
67.0            1
Name: count, dtype: int64

==================================================
Variable: MCQ240C
MCQ240C
NaN     134471
16.0         6
67.0         3
72.0         2
59.0         2
77.0         2
63.0         2
52.0         2
69.0         2
60.0         2
30.0         2
76.0         2
23.0         1
58.0         1
55.0         1
65.0         1
80.0         1
62.0         1
70.0         1
79.0         1
19.0         1
84.0         1
35.0         1
17.0         1
54.0         1
20.0         1
40.0         1
43.0         1
36.0         1
Name: count, dtype: int64

==================================================
Variable: MCQ240D
MCQ240D
NaN     134491
16.0         3
30.0         3
39.0         2
25.0         2
65.0         2
73.0         1
34.0         1
59.0         1
28.0         1
80.0         1
75.0         1
69.0         1
36.0         1
38.0         1
53.0         1
35.0         1
51.0         1
Name: count, dtype: int64

In [14]:
questionnaire[[
    "MCQ220",
    "MCQ230A",
    "MCQ240A",
    "MCQ240B",
    "MCQ240C",
    "MCQ240D"
]].head(20)

    MCQ220  MCQ230A  MCQ240A  MCQ240B  MCQ240C  MCQ240D
0      2.0      NaN      NaN      NaN      NaN      NaN
1      2.0      NaN      NaN      NaN      NaN      NaN
2      2.0      NaN      NaN      NaN      NaN      NaN
3      2.0      NaN      NaN      NaN      NaN      NaN
4      2.0      NaN      NaN      NaN      NaN      NaN
5      2.0      NaN      NaN      NaN      NaN      NaN
6      2.0      NaN      NaN      NaN      NaN      NaN
7      2.0      NaN      NaN      NaN      NaN      NaN
8      2.0      NaN      NaN      NaN      NaN      NaN
9      2.0      NaN      NaN      NaN      NaN      NaN
10     2.0      NaN      NaN      NaN      NaN      NaN
11     2.0      NaN      NaN      NaN      NaN      NaN
12     2.0      NaN      NaN      NaN      NaN      NaN
13     2.0      NaN      NaN      NaN      NaN      NaN
14     2.0      NaN      NaN      NaN      NaN      NaN
15     2.0      NaN      NaN      NaN      NaN      NaN
16     2.0      NaN      NaN      NaN      NaN      NaN
17     2.0      NaN      NaN      NaN      NaN      NaN
18     2.0      NaN      NaN      NaN      NaN      NaN
19     2.0      NaN      NaN      NaN      NaN      NaN

In [15]:
print("MCQ220")
print(questionnaire["MCQ220"].value_counts(dropna=False))

MCQ220
MCQ220
2.0    69121
NaN    59388
1.0     5946
9.0       59
7.0        1
Name: count, dtype: int64

In [16]:
print("MCQ230A")
print(questionnaire["MCQ230A"].value_counts(dropna=False))

MCQ230A
MCQ230A
NaN     129351
14.0       794
30.0       786
32.0       752
33.0       391
16.0       347
15.0       327
25.0       291
39.0       222
38.0       209
23.0       133
10.0       121
28.0       114
24.0       108
37.0        96
19.0        93
21.0        51
35.0        42
99.0        37
12.0        31
26.0        30
36.0        30
17.0        28
20.0        25
22.0        24
31.0        22
13.0        21
34.0        12
29.0        12
11.0        11
18.0         2
9.0          1
27.0         1
Name: count, dtype: int64

In [17]:
print("MCQ240A")
print(questionnaire["MCQ240A"].describe())

MCQ240A
count    115.000000
mean      65.130435
std       15.274403
min       16.000000
25%       57.000000
50%       68.000000
75%       78.000000
max       85.000000
Name: MCQ240A, dtype: float64

In [18]:
cancer = questionnaire[questionnaire["MCQ220"] == 1]

print(cancer.shape)

cancer[["MCQ220","MCQ230A","MCQ240A","MCQ240B","MCQ240C"]].head(20)

(5946, 1445)

     MCQ220  MCQ230A  MCQ240A  MCQ240B  MCQ240C
84      1.0      NaN      NaN      NaN      NaN
97      1.0      NaN      NaN      NaN      NaN
153     1.0      NaN      NaN      NaN      NaN
184     1.0      NaN      NaN      NaN      NaN
192     1.0      NaN      NaN      NaN      NaN
212     1.0      NaN      NaN      NaN      NaN
220     1.0      NaN      NaN      NaN      NaN
277     1.0      NaN      NaN      NaN      NaN
329     1.0      NaN      NaN      NaN      NaN
332     1.0      NaN      NaN      NaN      NaN
342     1.0      NaN      NaN      NaN      NaN
379     1.0      NaN      NaN      NaN      NaN
441     1.0      NaN      NaN      NaN      NaN
473     1.0      NaN      NaN      NaN      NaN
494     1.0      NaN      NaN      NaN      NaN
522     1.0      NaN      NaN      NaN      NaN
573     1.0      NaN      NaN      NaN      NaN
580     1.0      NaN      NaN      NaN      NaN
616     1.0      NaN      NaN      NaN      NaN
640     1.0      NaN      NaN      NaN      NaN

In [19]:
cancer = questionnaire[questionnaire["MCQ220"] == 1]

print(cancer.shape)

cancer[["MCQ220","MCQ230A","MCQ240A","MCQ240B","MCQ240C"]].head(20)

(5946, 1445)

     MCQ220  MCQ230A  MCQ240A  MCQ240B  MCQ240C
84      1.0      NaN      NaN      NaN      NaN
97      1.0      NaN      NaN      NaN      NaN
153     1.0      NaN      NaN      NaN      NaN
184     1.0      NaN      NaN      NaN      NaN
192     1.0      NaN      NaN      NaN      NaN
212     1.0      NaN      NaN      NaN      NaN
220     1.0      NaN      NaN      NaN      NaN
277     1.0      NaN      NaN      NaN      NaN
329     1.0      NaN      NaN      NaN      NaN
332     1.0      NaN      NaN      NaN      NaN
342     1.0      NaN      NaN      NaN      NaN
379     1.0      NaN      NaN      NaN      NaN
441     1.0      NaN      NaN      NaN      NaN
473     1.0      NaN      NaN      NaN      NaN
494     1.0      NaN      NaN      NaN      NaN
522     1.0      NaN      NaN      NaN      NaN
573     1.0      NaN      NaN      NaN      NaN
580     1.0      NaN      NaN      NaN      NaN
616     1.0      NaN      NaN      NaN      NaN
640     1.0      NaN      NaN      NaN      NaN

In [20]:
# Check whether MCQ230A and MCQ240A have ANY non-null values

print("MCQ230A non-null values:", questionnaire["MCQ230A"].notna().sum())
print("MCQ240A non-null values:", questionnaire["MCQ240A"].notna().sum())
print("MCQ240B non-null values:", questionnaire["MCQ240B"].notna().sum())
print("MCQ240C non-null values:", questionnaire["MCQ240C"].notna().sum())

MCQ230A non-null values: 5164
MCQ240A non-null values: 115
MCQ240B non-null values: 14
MCQ240C non-null values: 44

In [21]:
print(questionnaire["MCQ230A"].value_counts().sort_index())

MCQ230A
9.0       1
10.0    121
11.0     11
12.0     31
13.0     21
14.0    794
15.0    327
16.0    347
17.0     28
18.0      2
19.0     93
20.0     25
21.0     51
22.0     24
23.0    133
24.0    108
25.0    291
26.0     30
27.0      1
28.0    114
29.0     12
30.0    786
31.0     22
32.0    752
33.0    391
34.0     12
35.0     42
36.0     30
37.0     96
38.0    209
39.0    222
99.0     37
Name: count, dtype: int64

In [22]:
questionnaire["MCQ230A"].unique()

array([nan, 32., 28., 26., 14., 36., 25., 33., 99., 39., 17., 16., 23.,
       30., 15., 34., 24., 19., 38., 35., 12., 37., 31., 21., 20., 10.,
       11., 22., 13.,  9., 18., 29., 27.])

In [23]:
import os

files = sorted(os.listdir())

for file in files:
    print(file)

38575571_dictionary_drug_codes.csv
38575574_dictionary_harmonized_categories.csv
41730855_dictionary_drug_codes.csv
41730858_dictionary_harmonized_categories.csv
41730861_dictionary_nhanes.csv
41730888_nhanes_inconsistencies_documentation.xlsx
41731260_dictionary_nhanes.csv
46382449_nhanes_inconsistencies_documentation.xlsx
46382458_w - nhanes_1988_2018.RData
46382461_w - nhanes_1988_2018.RData
chemicals_clean.csv
chemicals_unclean.csv
comments_clean.csv
comments_unclean.csv
demographics_clean.csv
demographics_unclean.csv
dietary_clean.csv
dietary_unclean.csv
example_0 - merge_datasets_together.Rmd
example_1 - account_for_nhanes_design.Rmd
example_2 - calculate_summary_statistics.Rmd
example_3 - run_multiple_regressions.Rmd
m - nhanes_1988_2018.R
medications_clean.csv
medications_unclean.csv
mortality_clean.csv
mortality_unclean.csv
occupation_clean.csv
occupations_unclean.csv
questionnaire_clean.csv
questionnaire_unclean.csv
response_clean.csv
response_unclean.csv
weights_clean.csv
weights_unclean.csv

In [24]:
dictionary = pd.read_csv("41730861_dictionary_nhanes.csv", low_memory=False)

print(dictionary.shape)
dictionary.head()

(5153, 9)

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
0,1,SEQN,Respondent sequence number,mortality,NaN,NaN,NaN,NaN,NaN
1,2,SEQN_new,Respondent sequence number that includes an identifier for NHANES III and NHANES continuous,mortality,NaN,NaN,NaN,NaN,NaN
2,3,ELIGSTAT,Eligibility Status for Mortality Follow-up,mortality,NaN,NaN,NaN,NaN,NaN
3,4,MORTSTAT,Final Mortality Status,mortality,NaN,NaN,NaN,NaN,NaN
4,5,UCOD_LEADING,Underlying Cause of Death Recode from UCOD_113; Leading Causes,mortality,NaN,NaN,NaN,NaN,NaN

In [25]:
# Look up MCQ220
dictionary[dictionary["variable_codename_use"] == "MCQ220"]

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
2734,2735,MCQ220,Ever told you had cancer or malignancy,questionnaire,NaN,NaN,NaN,NaN,NaN

In [26]:
dictionary[dictionary["variable_codename_use"] == "MCQ230A"]

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
2735,2736,MCQ230A,1st cancer - what kind was it?,questionnaire,NaN,NaN,NaN,NaN,NaN

In [27]:
dictionary[dictionary["variable_codename_use"] == "MCQ240A"]

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
2739,2740,MCQ240A,Age when bladder cancer first diagnosed,questionnaire,NaN,NaN,NaN,NaN,NaN

In [28]:
print(mortality.columns.tolist())

['Unnamed: 0', 'SEQN', 'SEQN_new', 'ELIGSTAT', 'MORTSTAT', 'UCOD_LEADING', 'DIABETES', 'HYPERTEN', 'PERMTH_INT', 'PERMTH_EXM', 'SDDSRVYR', 'VNELIGSTAT', 'VNMORTSTAT', 'VNUCOD_LEADING', 'VNDIABETES', 'VNHYPERTEN']

In [29]:
dictionary[
    dictionary["variable_description_use"]
    .str.contains("breast", case=False, na=False)
]

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
33,34,DRABF,Breast-fed Infant (either day),dietary,NaN,NaN,NaN,NaN,NaN
2748,2749,MCQ240E,Age when breast cancer was first diagnosed,questionnaire,NaN,NaN,NaN,NaN,NaN
3007,3008,RHD230,How many of your children did you breast feed for at least 1 month?,questionnaire,NaN,NaN,NaN,NaN,NaN
3036,3037,RHQ200,Now breastfeeding a child?,questionnaire,NaN,NaN,NaN,NaN,NaN
3037,3038,RHQ205,Breastfed any child at least 1 month?,questionnaire,NaN,NaN,NaN,NaN,NaN
3038,3039,RHQ210,Breastfed any of your children?,questionnaire,NaN,NaN,NaN,NaN,NaN
3039,3040,RHQ240A,Reason not breastfed - job-scheduling difficulties,questionnaire,NaN,NaN,NaN,NaN,NaN
3040,3041,RHQ240B,Reason not breastfed - mother's physical-medical difficulties,questionnaire,NaN,NaN,NaN,NaN,NaN
3041,3042,RHQ240C,Reason not breastfed - child's physical-medical difficulties,questionnaire,NaN,NaN,NaN,NaN,NaN
3042,3043,RHQ240D,Reason not breastfed - preferred bottle,questionnaire,NaN,NaN,NaN,NaN,NaN
3043,3044,RHQ240E,Reason not breastfed - didn't know how,questionnaire,NaN,NaN,NaN,NaN,NaN
3044,3045,RHQ240F,Reason not breastfed - other reasons,questionnaire,NaN,NaN,NaN,NaN,NaN

In [30]:
dictionary[
    dictionary["comment_codename_use"].notna()
].head(20)

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
3123,3124,LBXBSE2,Serum selenium replicate 2 (ug/L),chemicals,(ug/L),7782-49-2,LBDBSE2LC,Dietary Components,DCs
3124,3125,LBDTLY1,total Lycopene replicate 1 (ug/dL),chemicals,(ug/dL),502-65-8,LBDLYC1LC,Dietary Components,DCs
3125,3126,LBDTLY2,total Lycopene replicate 2 (ug/dL),chemicals,(ug/dL),502-65-8,LBDLYC2LC,Dietary Components,DCs
3126,3127,LBXALC1,Serum alpha carotene replicate 1 (ug/dL),chemicals,(ug/dL),7488-99-5,LBDALC1LC,Dietary Components,DCs
3127,3128,LBXALC2,Serum alpha carotene replicate 2 (ug/dL),chemicals,(ug/dL),7488-99-5,LBDALC2LC,Dietary Components,DCs
3128,3129,LBXCBC,Serum cis-Beta carotene (ug/dL),chemicals,(ug/dL),13312-52-2,LBDCBCLC,Dietary Components,DCs
3129,3130,LBXCRY1,Serum beta cryptoxanthin replicate 1 (ug/dL),chemicals,(ug/dL),472-70-8,LBDCRY1LC,Dietary Components,DCs
3130,3131,LBXCRY2,Serum beta cryptoxanthin replicate 2 (ug/dL),chemicals,(ug/dL),472-70-8,LBDCRY2LC,Dietary Components,DCs
3131,3132,LBXLUZ1,Serum combined lutein/zeaxanthin replicate 1 (ug/dL),chemicals,(ug/dL),38327-39-8/144-68-3,LBDLUZ1LC,Dietary Components,DCs
3132,3133,LBXLUZ2,Serum combined lutein/zeaxanthin replicate 2 (ug/dL),chemicals,(ug/dL),38327-39-8/144-68-3,LBDLUZ2LC,Dietary Components,DCs
3133,3134,LBXVIA1,Vitamin A replicate 1 (ug/dL),chemicals,(ug/dL),68-26-8,LBDVIA1LC,Dietary Components,DCs
3134,3135,LBXVIA2,Vitamin A replicate 2 (ug/dL),chemicals,(ug/dL),68-26-8,LBDVIA2LC,Dietary Components,DCs
3135,3136,URXUCD2,Urinary cadmium replicate 2 (ng/mL),chemicals,(ng/mL),7440-43-9,URDUCD2LC,Metals,Metals
3136,3137,LBXSCA1,Serum total calcium replicate 1 (mg/dL),chemicals,(mg/dL),7440-70-2,LBXSCA1LC,Dietary Components,DCs
3137,3138,LBXBPB1,Blood lead replicate 1 (ug/dL),chemicals,(ug/dL),7439-92-1,LBDBPB1LC,Metals,Metals
3138,3139,LBXBPB2,Blood lead replicate 2 (ug/dL),chemicals,(ug/dL),7439-92-1,LBDBPB2LC,Metals,Metals
3139,3140,LBXSKSI1,Serum potassium replicate 1 (mmol/L),chemicals,(mmol/L),7440-09-7,LBXSKSI1LC,Dietary Components,DCs
3140,3141,LBXBSE1,Serum selenium replicate 1 (ug/L),chemicals,(ug/L),7782-49-2,LBDBSE1LC,Dietary Components,DCs
3141,3142,LBXVIC1,Serum vitamin C replicate 1 (mg/dL),chemicals,(mg/dL),50-81-7,LBDVIC1LC,Dietary Components,DCs
3142,3143,LBXVIC2,Serum vitamin C replicate 2 (mg/dL),chemicals,(mg/dL),50-81-7,LBDVIC2LC,Dietary Components,DCs

In [31]:
dictionary[
    dictionary["variable_codename_use"] == "MCQ230A"
]

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
2735,2736,MCQ230A,1st cancer - what kind was it?,questionnaire,NaN,NaN,NaN,NaN,NaN

In [32]:
dictionary[dictionary["variable_codename_use"]=="MCQ230A"][["variable_codename_use","variable_description_use","comment_codename_use"]]

,variable_codename_use,variable_description_use,comment_codename_use
2735,MCQ230A,1st cancer - what kind was it?,NaN

In [33]:
dictionary[dictionary.astype(str).apply(
    lambda x: x.str.contains("MCQ230A", case=False, na=False).any(), axis=1
)]

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
2675,2676,MCD240A,How old {were you/was SP} when {cancer in MCQ230a} was first diagnosed?,questionnaire,NaN,NaN,NaN,NaN,NaN
2735,2736,MCQ230A,1st cancer - what kind was it?,questionnaire,NaN,NaN,NaN,NaN,NaN

In [34]:
dictionary[
    dictionary["variable_description_use"].str.contains(
        "breast cancer", case=False, na=False
    )
]

,Unnamed: 0,variable_codename_use,variable_description_use,in_dataset,units,cas_num,comment_codename_use,chemical_family,chemical_family_shorten
2748,2749,MCQ240E,Age when breast cancer was first diagnosed,questionnaire,NaN,NaN,NaN,NaN,NaN

In [35]:
breast_cancer = questionnaire[questionnaire["MCQ240E"].notna()]

print("Number of breast cancer patients:", breast_cancer.shape[0])

breast_cancer[["MCQ220", "MCQ230A", "MCQ240E"]].head(20)

Number of breast cancer patients: 823

       MCQ220  MCQ230A  MCQ240E
33274     1.0     14.0     73.0
33288     1.0     14.0     56.0
33397     1.0     14.0     44.0
33428     1.0     14.0     75.0
33570     1.0     14.0     76.0
33657     1.0     14.0     61.0
33785     1.0     14.0     52.0
33835     1.0     14.0     66.0
33928     1.0     14.0     63.0
33980     1.0     14.0     63.0
34008     1.0     14.0     52.0
34314     1.0     14.0     45.0
34412     1.0     14.0     32.0
34570     1.0     14.0     73.0
34635     1.0     14.0     67.0
34852     1.0     14.0     59.0
35119     1.0     14.0     69.0
35284     1.0     14.0     60.0
35671     1.0     14.0     71.0
35745     1.0     14.0  99999.0

# Verification Conclusion

The NHANES dataset contains variables that identify individuals diagnosed with breast cancer.

The questionnaire variables MCQ220 and MCQ230A enable extraction of breast cancer patients.

Therefore, NHANES is an appropriate dataset for developing machine learning models for breast cancer prediction.